#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
#
#Keyb
sxhkd &
nm-applet &

#Polybar and wallpaper 
#$HOME/.config/polybar/launch.sh <- Default
#
$bash .config/polybar/pseudo/launch.sh &

${HOME}/.fehbg

#Picom
picom --experimental-backends &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5

#Bspwm Cgf
bspc config border_width        0
bspc config window_gap          6
bspc config normal_border_color \#0E0E0E
bspc config focused_border_color \#2D2D2D

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#Bspwm Rules
bspc rule -a firefox desktop='^1' follow=off focus=off
bspc rule -a discord desktop='^2' follow=off focus=off
bspc rule -a "" desktop='^3' follow=off focus=off fullscreen=on
bspc rule -a Code desktop='^4' follow=off focus=off
bspc rule -a Gimp desktop='^5' follow=off focus=off
bspc rule -a Toolkit desktop='^1' state=floating follow=on
bspc rule -a Picture-in-Picture state=floating
